version: '2'
services:
  ras-respondent:
    build: 
      context: ../
    environment:
      - server.port=8080
      - eureka.client.serviceUrl.defaultZone=http://ras-registry:8761/eureka/
    networks:
      - ras

networks:
  ras:
